### ISSUE TITLE
Data import isn't working 

### ISSUE THREAD

**Issue by MrZombie69232** [biasvariancelabs/aitlas#6]
Hi,
I imported the dataset using the `from aitlas.datasets import AIRSDataset` but didn't find any. 

Any help is appreciated!
Thanks

**Comment by simidjievskin** [comment]
Hi @MrZombie69232 -  since we are not the authors of the datasets (and a variety of other reasons) we can't host them. You will need to first download the dataset yourself, in this case for AIRS from here : https://www.airs-dataset.com . In all of the dataset classes we provide the url where you can find the data or you can also use this http://eodata.bvlabs.ai to get the necessary info. After you have the data downloaded you can use it with loaders we provide.  
Btw can you paste the error you get? 
Hope this helps. Cheers

**Comment by MrZombie69232** [comment]
Hi @simidjievskin , 
Thank you very much for quick response! 
Actually there wasn't any error but no data . I thought the data is imported from the software itself. 
I have another request " Will it be possible to have pre-trained models as well? Like the saved models on rooftops detection on different datasets so that we can use them to infer and if needed train. 

Also, can you please include vision transformer too ? 

Thank you very much for creating this wonderful framework. 

Thank & Regards
Satyam

**Comment by simidjievskin** [comment]
No worries :) 
Re models: We are cooking something, which will be available very soon. Stay tuned :) 

cheers
